
name: Actualizar app.py automáticamente

on:
  workflow_dispatch:     # Esto permite el botón manual
  schedule:
    - cron: '02 15 * * *' 

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Asegúrate de haber creado este secreto

      - name: Hacer un cambio en app.py
        run: 'echo "# Última actualización: $(date -u)" >> app.py'
      - name: Subir cambios a GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add app.py
          git commit -m "Actualización automática de app.py" || echo "Sin cambios que subir"
          git push origin HEAD
