name: Actualizar app.py automáticamente

on:
  schedule:
    - cron: '0 7 * * *'  # Todos los días a las 7am UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Ejecutar script de actualización
        run: |
          echo "# Última actualización: $(date)" >> app.py

      - name: Commit y push si hay cambios
        run: |
          git add app.py
          if git diff --cached --quiet; then
            echo "Sin cambios. No se hace commit."
          else
            git commit -m "Actualización automática de app.py"
            git push
          fi
